server:
  port: 8098

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        debug: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    disable-swagger-default-url: true

logging:
  level:
    root: DEBUG
    com.example.notification: DEBUG
    org.springframework.mail: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot.web.embedded.tomcat: DEBUG